___

<img src='../devf-logo.jpg' />

# Indexación y selección con Numpy



In [1]:
import numpy as np

In [2]:
#Crea un arreglo simple
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Indexación y selección con corchetes

In [4]:
#Regresa el valor en determinado índice
arr[8]

8

In [5]:
#Regresa valores en un determinado rango
arr[1:5]

array([1, 2, 3, 4])

In [6]:
#Regresa valores en un determinado rango
arr[0:5]

array([0, 1, 2, 3, 4])

## Trabajando con arreglos de dos dimensiones (matrices)

El formato general es **arr_2d[fila][columna]** o **arr_2d[fila,col]**.

In [7]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [8]:
#Seleccionando fila
arr_2d[1]


array([20, 25, 30])

In [9]:
# Obtener valor individual
arr_2d[1][0]

20

In [10]:
# Obtener valor individual
arr_2d[1,0]

20

In [11]:
# Cortar una matriz

arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

### Indexación elegante

La indexación elegante te permite seleccionar filas o columnas enteras fuera de orden, crearemos un nuevo arreglo para demostrarlo:

In [12]:
arr2d = np.zeros((10,10))

In [13]:
arr_length = arr2d.shape[1]
arr_length

10

In [14]:

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

La Indexación elegante te permite lo siguiente

In [15]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [16]:
#Permite en cualquier orden
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## Selección

In [17]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [19]:
bool_arr = arr>4

In [20]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [21]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [22]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# ¡Excelente trabajo!
