# Numpy

In [1]:
import numpy as np

In [2]:
lista = [1,2,3]
lista

[1, 2, 3]

In [3]:
np.array(lista)

array([1, 2, 3])

In [4]:
mi_matriz = [[1,2,3],[4,5,6],[7,8,9]]
mi_matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(mi_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
arr2 = np.linspace(0,10,50)
arr2.dtype

dtype('float64')

In [17]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.random.rand(3,2)

array([[0.19358745, 0.74631107],
       [0.01732959, 0.71899163],
       [0.21823423, 0.78369795]])

# randint

In [26]:
np.random.randint(1,100)

99

In [27]:
np.random.randint(1,100,(3,3))

array([[33,  2, 57],
       [91, 56, 61],
       [65,  7, 24]])

In [28]:
arr = np.arange(25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [34]:
ranarr = np.random.randint(0,50,10)
ranarr

array([36, 23,  7,  4,  7,  4, 47, 10, 32, 25])

In [35]:
ranarr.max()

47

In [36]:
ranarr.argmax()

6

In [37]:
ranarr.min()

4

In [38]:
ranarr.argmin()

3

In [41]:
arr.shape

(25,)

In [46]:
arr.reshape(1,25).shape

(1, 25)

In [43]:
arr.shape

(25,)

In [47]:
arr.dtype

dtype('int32')