# Indexación y Selección con Numpy

In [1]:
import numpy as np

In [8]:
arr = np.arange(0,11)

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[8]

9

In [10]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [11]:
arr2d = np.array(([1,2,3],[4,5,6],[7,8,9]))

arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr2d[1][:2]

array([4, 5])

In [17]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [20]:
bool_arr = arr > 4

In [21]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [22]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [23]:
x = 2

In [24]:
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])